### ISSUE TITLE
Run example throw an exception

### ISSUE THREAD

**Issue by randomhuangpl** [SimonWang9610/flutter_slidable_panel#5] opened 2023-09-21 08:49 UTC
Hello, this slidable panel is so good. 
I'm use Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64.
While run example demo throw an exception,thanks

<details>
<summary>Exception Log</summary>
 
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderSemanticsAnnotations#4dcc8 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 3567 pos 12: '!_needsLayout'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3567:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#4      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4291:14)
#5      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#6      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#7      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#8      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4291:14)
#9      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#10     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#11     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#12     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#13     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#14     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#15     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#16     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#17     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#18     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#19     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#20     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#22     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#23     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#24     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#25     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#26     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#27     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#28     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4291:14)
#29     RenderSliverMultiBoxAdaptor.visitChildrenForSemantics (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:402:11)
#30     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#31     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#32     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#33     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#34     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#35     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#36     Iterable.forEach (dart:core/iterable.dart:347:35)
#37     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:247:10)
#38     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#39     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#40     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#41     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#42     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3617:11)
#43     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#44     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#45     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#46     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#47     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#48     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#49     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#50     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#51     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#52     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#53     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#54     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#55     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#56     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#57     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#58     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#59     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#60     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#61     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#62     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#63     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#64     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#65     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#66     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#67     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#68     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#69     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#70     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#71     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#72     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#73     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#74     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4291:14)
#75     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#76     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#77     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#78     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#79     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#80     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#81     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#82     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#83     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#84     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#85     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#86     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#87     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#88     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#89     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#90     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#91     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#92     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#93     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#94     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#95     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#96     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#97     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3617:11)
#98     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#99     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#100    ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4291:14)
#101    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#102    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#103    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#104    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#105    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#106    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#107    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#108    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#109    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#110    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#111    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#112    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#113    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#114    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#115    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#116    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#117    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#118    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#119    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#120    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#121    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#122    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#123    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#124    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#125    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#126    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#127    RenderOffstage.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3760:11)
#128    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#129    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#130    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#131    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#132    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#133    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#134    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#135    _RenderTheater.visitChildrenForSemantics (package:flutter/src/widgets/overlay.dart:1151:14)
#136    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#137    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#138    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#139    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#140    RenderAbsorbPointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3864:11)
#141    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#142    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#143    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#144    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#145    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#146    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#147    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#148    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#149    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#150    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#151    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#152    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#153    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#154    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#155    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#156    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#157    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#158    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#159    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#160    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#161    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#162    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#163    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#164    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#165    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#166    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#167    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#168    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#169    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#170    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#171    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#172    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#173    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#174    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#175    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#176    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#177    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#178    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#179    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#180    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#181    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#182    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#183    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#184    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#185    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#186    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#187    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4284:11)
#188    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#189    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3583:61)
#190    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#191    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3724:5)
#192    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3581:5)
#193    RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3533:41)
#194    PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1265:16)
#195    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:21)
#196    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#197    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#198    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#199    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#200    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#201    _invoke (dart:ui/hooks.dart:170:13)
#202    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#203    _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
</details>

**Comment by SimonWang9610** [comment] 2023-09-21 13:01
Hi, thanks for reporting.

Which example did you try?

Looks like it is related to semantics staff.

**Comment by SimonWang9610** [comment] 2023-09-21 17:27
@randomhuangpl 
Could you try to add `excludeFromSemantics: true` in the `lib/src/widgets/slidable_panel.dart: line 138 -> GestureDetector`?

Also, for the example `example/lib/list_slidable.dart`, please also set `addSematicIndexes: false` at the line of 24.

If it still throws the same error, please tell me.

I guess it is related to the [IgnorePointer break change](https://docs.flutter.dev/release/breaking-changes/ignoringsemantics-migration)

There is no exception thrown when running the example for Flutter 3.10, so it would be great if you could try it by yourself and report what you get, as my working version is 3.10, and I cannot upgrade it right now.

**Comment by randomhuangpl** [comment] 2023-09-22 03:28
@SimonWang9610  thanks for reply.
Still have same problem.
![image](https://github.com/SimonWang9610/flutter_slidable_panel/assets/113404168/47c7486a-7e4d-4716-8fa0-62b415dc424a)
![image](https://github.com/SimonWang9610/flutter_slidable_panel/assets/113404168/c97e11d5-c501-4fa5-b4b2-44d906a09577)
![image](https://github.com/SimonWang9610/flutter_slidable_panel/assets/113404168/d835a7b2-1085-4070-9f1a-1ed5ad604cb6)

Here's a convenient tool for switching Flutter SDK versions if you need it. （https://github.com/fluttertools/sidekick）

**Comment by SimonWang9610** [comment] 2023-09-22 13:38
@randomhuangpl 

Thanks for your feedback.

I will try upgrading Flutter on my other computer to diagnose this issue.

I never thought about the semantic staff before, so it is also a good time to do it.

**Comment by SimonWang9610** [comment] 2023-09-25 14:20
@randomhuangpl 
I tried to run the example using Flutter 3.13.5 on Windows, but I could not reproduce the exception. 
Not sure if this issue is dependent on the Mac platform, so I will keep an eye on it.

**Comment by randomhuangpl** [comment] 2023-09-27 10:40
@SimonWang9610
I retested it again, and the error only appears on the iOS simulator. Work well on a real iPhone device.

**Comment by SimonWang9610** [comment] 2023-09-27 12:15
> @SimonWang9610 I retested it again, and the error only appears on the iOS simulator. Work well on a real iPhone device.

Great! I can reproduce this issue on the iOS simulator, and I will try to fix it.

It seems not related to the Flutter version.

**Comment by SimonWang9610** [comment] 2023-09-28 01:07
fixed by https://github.com/SimonWang9610/flutter_slidable_panel/pull/6

**Closed as completed by SimonWang9610** 2023-09-28 01:07 UTC
